# Read the Docs configuration
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

# Build the HTML docs from the Sphinx configuration
sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false

# Install docs dependencies before building
python:
  install:
    - requirements: docs/requirements.txt
